# version attribute is removed
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    networks:
      - kafka_net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    networks:
      - kafka_net
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      # --- THIS IS THE NEW, MORE ROBUST HEALTHCHECK ---
      test: ["CMD", "cub", "kafka-ready", "-b", "localhost:9092", "1", "1"]
      interval: 10s
      timeout: 5s
      retries: 10 # Increased retries to give Kafka more time to start
      start_period: 40s # Give Kafka a generous grace period before starting checks

  # The producer and consumer services remain unchanged from the last version
  producer:
    build:
      context: ./producer
    networks:
      - kafka_net
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'
      TOPIC_NAME: 'events_topic'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      # --- INCREASE THE START PERIOD ---
      start_period: 30s # Increased to 30 seconds

  consumer:
    build:
      context: ./consumer
    networks:
      - kafka_net
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'
      TOPIC_NAME: 'events_topic'
      CONSUMER_GROUP: 'logging_group'

networks:
  kafka_net:
    driver: bridge